apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: catalogapiowner
  description: catalog owner
spec:
  type: business-unit
  profile:
    displayName: Catalog API Team
  children:
    - other

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalogapi
  description: |
    Globalcorp storefront main catalogapi.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    harness.io/pipelines: |
      Build and Deploy: https://workshop.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/module/cd/orgs/default/projects/globalcorp/pipelines/GoodApi/pipeline-studio?storeType=INLINE

  tags:
    - globalcorp
spec:
  type: service
  owner: catalogapiowner
  lifecycle: experimental

